# ===============================
# = DEV
# ===============================
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/PETCLINIC_DB?useSSL=false
    # Windoows
    # url : jdbc:mysql://localhost:3306/PETCLINIC_DB?useSSL=false&serverTimezone=UTC
    username: root
    password:

    platform: mysql
    initialization-mode: always

  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none
    open-in-view: false
    show-sql: true
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect